### PR TITLE
Designed review page

### PR DESCRIPTION
**Pull request by SarveshLimaye**
Resolved issue #13 

screencapture-127-0-0-1-5500-reviews-html-2021-07-13-11_34_33

### CODE REVIEW

**Comment by sifa123** [comment]
Thanks @SarveshLimaye

**Comment by sifa123** [comment]
@SarveshLimaye I don't think this review page is exactly the same as you give. Please check it again.

**Comment by SarveshLimaye** [comment]
@sifa123 Could you pls provide me with screenshot so that I could look into it . I checked on my local system it is working fine

**Comment by sifa123** [comment]
yeah sure 
Screenshot (169)
Screenshot (170)

**Pull request merged**
