### PR TITLE
Image Slider Added

### LINKED ISSUE #22: Image Slider below navbar
I would like to add the image slider below the navbar which will contain different pictures
Please assign me this issue under DCP'21

### PR DESCRIPTION
**Pull request by neha030**
I have added the image slider below the navbar 
Image change by clicking the black arrow and even by sliding 
fixes #22 
Please review 

Screenshot (225)
Screenshot (223)
Screenshot (226)

### CODE REVIEW

**Comment by neha030** [comment]
It's showing branch conflicts how to resolve this ??
Please help

**Comment by DarshGupta1910** [comment]
Hey @neha030, 
Not sure but I think the changes you have made should be done under gallery.html and gallery.css. That's why it's showing a conflict.

**Comment by neha030** [comment]
> Hey @neha030,
> Not sure but I think the changes you have made should be done under gallery.html and gallery.css. That's why it's showing a conflict.

I have deleted the conflicting file index.html and added all the changes to gallery.html and gallery.css 
Please review

**Comment by sifa123** [comment]
@neha030 We will add these slide images only for home page. If you face any problem, you can delete this pull request, create another one, and you can also ask for help or give it to other contributors.

**Comment by neha030** [comment]
> @neha030 We will add these slide images only for home page. If you face any problem, you can delete this pull request, create another one, and you can also ask for help or give it to other contributors.

Ok i will close this PR and will make a new one...adding the image slider in index.html and style.css

**Pull request closed without merging**
