### PR TITLE
Added Home Page

### PR DESCRIPTION
**Pull request by K-jais**
It resolves issue #1 

Designed the web site's home page according to the diagram you have provided in the slack channel.

Its working video,

https://user-images.githubusercontent.com/75881393/126998577-c83c46a1-67c8-48b0-9336-9b8115a82fa4.mp4

### CODE REVIEW

**Comment by K-jais** [comment]
Please review this PR before merging any other PR.
Its link - https://k-jais.github.io/Dev-Kitchen/
@sifa123

**Comment by sifa123** [comment]
@K-jais Good work but here is something you have to do.... keep our updated navbar and footer with your 2nd footer that contain about us, gallery ,.. , you will see this in our repo. Your color combination doesn't look so good, also text sizes and make the edit slider image so that the text can easily seen.
Also you will see a about section on our home page you should keep after the slide section and yours EXECUTIVE CHEF section you can add that on about page, it will look better. Then add menu, weekly served and then add ours service section, finally customer reviews.
Navbar(1,2)> Slide > served with love(about section) > menu> Weekly served > Service >Customer Reviews > Footer(1,2) 
Please Make this changes

**Comment by K-jais** [comment]
@sifa123 I have to change the navbar and footer in the home page or not?

And if I have to change then change it to which design?

**Comment by K-jais** [comment]
@sifa123 And what should I do with the executive chef section?

**Comment by sifa123** [comment]
> @sifa123 I have to change the navbar and footer in the home page or not?
> 
> And if I have to change then change it to which design?

Add this navbar
Screenshot (181)

and footer 

Screenshot (182)
before that footer you can add your designed footer that contains about us, gallery, business hours.

**Comment by sifa123** [comment]
> @sifa123 And what should I do with the executive chef section?

we can add this on about us page.

**Comment by K-jais** [comment]
I have done the respective changes.
@sifa123

**Comment by K-jais** [comment]
@sifa changed that thing

**Comment by K-jais** [comment]
Please now review this PR.

**Comment by K-jais** [comment]
@sifa123

**Pull request merged**
