### PR TITLE
Update top nav bar to add responsiveness

### PR DESCRIPTION
**Pull request by ri-tae-ka**
### Description
I have added responsiveness top the top navbar and worked on the styling to get rid of the extra white space left in the right side of the website that appeared earlier.

### CODE REVIEW

**Comment by ri-tae-ka** [comment]
Please do review my code and add any other Level tags that may be necessary.

**Comment by sifa123** [comment]
Yeah the top navbar looks good to me!! Thanks @ri-tae-ka

**Comment by ri-tae-ka** [comment]
@sifa123 as it was under DCP do i need to fill a form after successful merging of the pr?
If so please do share the form with me.

**Comment by ri-tae-ka** [comment]
closes #44

**Pull request merged**
